### ISSUE TITLE
1. Remove SequenceModelElement before single basic parser model elements

### ISSUE THREAD

**Issue by ernstleierzopf** [ait-aecid/aecid-parsergenerator#3]
current behavior: 
model = SequenceModelElement('sequence0', [FixedDataModelElement('fixed1', b'fixed data')]

expected behavior:
model = FixedDataModelElement('fixed0', b'fixed data')

**Comment by landauermax** [comment]
This is desired behavior and only occurs at the root node. The goal was to have all parsers start consistently with Sequences or FirstMatchModels. Inside the parser, this issue does not occur. For example, the input
a b
a c
yields the following parser, where single basic parser model elements are not in SequenceModelElements (needs appropriate PGConfig):
        model = SequenceModelElement('sequence1', [
                FixedDataModelElement('fixed2', b'a '),
                FirstMatchModelElement('firstmatch3', [
                        FixedDataModelElement('fixed4', b'c'),
                        FixedDataModelElement('fixed5', b'b')])])

**Comment by ernstleierzopf** [comment]
Ok. I have changed the unittests to support this desired behavior.

**Comment by landauermax** [comment]
Thanks, I will close this issue.
