### ISSUE TITLE
2. DecimalIntegerValueModelElement PEP8

### ISSUE THREAD

**Issue by ernstleierzopf** [ait-aecid/aecid-parsergenerator#4]
The DecimalIntegerValueModelElement is currently not PEP8 conform.

current behavior:
model = DecimalIntegerValueModelElement('integer0', value_sign_type = DecimalIntegerValueModelElement.SIGN_TYPE_OPTIONAL)

expected behavior:
current behavior:
model = DecimalIntegerValueModelElement('integer0', value_sign_type=DecimalIntegerValueModelElement.SIGN_TYPE_OPTIONAL)

**Comment by landauermax** [comment]
Fixed
