### ISSUE TITLE
4. Numbering of the component names are inconsistent

### ISSUE THREAD

**Issue by ernstleierzopf** [ait-aecid/aecid-parsergenerator#6]
Numbering of the component's names is inconsistent. For example sub_trees always begin with 0 and the model always begins with 1.

current behavior:
sub_tree0 = SequenceModelElement('sequence0', [...])

# other config without sub_trees
model = SequenceModelElement('sequence1', [...])

expected behavior:
sub_tree0 = SequenceModelElement('sequence0', [...])

# other config without sub_trees
model = SequenceModelElement('sequence0', [...])

**Comment by landauermax** [comment]
This needs to be fixed by @hoeldg in the next version. We will not include subtrees in V1.0

**Comment by ernstleierzopf** [comment]
Ok. So numbering starts at 1 and Subtrees will also start with 1? I will have to fix these in the unittests.

**Comment by landauermax** [comment]
No sorry, you are right, since this issue is about the numbering of parsing elements, not subtrees. I will fix it for V1.0.
