### ISSUE TITLE
6. DecimalFloatValueModelElement does not use sign type optional

### ISSUE THREAD

**Issue by ernstleierzopf** [ait-aecid/aecid-parsergenerator#8]
The DecimalFloatValueModelElement should use the sign type optional like the DecimalIntegerValueModelElement.

current behavior:
model = DecimalFloatValueModelElement('float0')

expected behavior:
model = DecimalFloatValueModelElement('float0', value_sign_type=DecimalFloatValueModelElement.SIGN_TYPE_OPTIONAL)

**Comment by landauermax** [comment]
Fixed
